"""
Bitcoin Breakout Strategy Dashboard  v7.10

Pre-computed: loads pickle on startup, zero computation at runtime.
Tabs: Strategies | Trades | FAQ
Dark theme, 1920×1080 design target.
Stop loss: fixed at Low[T]. Entry filter: Open[T+1] > Low[T].
"""

import pickle, math, re
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import streamlit as st
# NOTE: streamlit-plotly-events was tested but its bundled Plotly.js (~v2)
# cannot render go.Heatmap traces generated by Plotly 6.  Falling back to
# the invisible-scatter overlay method with st.plotly_chart on_select.

# ─── Paths ───
APP_DIR = Path(__file__).resolve().parent
PKL_PATH = APP_DIR / "data" / "precomputed.pkl"
FAQ_PATH = APP_DIR / "faq.md"
TOOLTIPS_PATH = APP_DIR / "tooltips.md"


# ═══════════════════════════════════════════════
# THEME
# ═══════════════════════════════════════════════

THEME = {
    "bg": "#0D1117", "surface": "#161B22", "surface2": "#1C2333",
    "border": "#30363D", "text": "#E6EDF3", "text_muted": "#8B949E",
    "heading": "#E6EDF3", "subheading": "#8B949E",
    "gold": "#C9A84C", "gold_bg": "rgba(201,168,76,0.12)",
    "green": "#3FB950", "red": "#F85149",
    "grid": "#21262D", "chart_bg": "#0D1117", "chart_paper": "#0D1117",
    "entry_band": "#00BCD4", "exit_band": "#FF9800",
    "marker_buy_sell": "#FFB800",
    "bb_fill_alpha": 0.25, "trade_fill_alpha": 0.15,
}
def T(): return THEME
def _hex_to_rgb(h):
    return int(h[1:3], 16), int(h[3:5], 16), int(h[5:7], 16)


# ═══════════════════════════════════════════════
# DATA LOADING
# ═══════════════════════════════════════════════

@st.cache_resource
def load_precomputed():
    with open(PKL_PATH, "rb") as f:
        return pickle.load(f)

def _parse_md_sections(path):
    text = path.read_text(encoding="utf-8")
    sections, current, lines = {}, None, []
    for line in text.split("\n"):
        if line.startswith("## "):
            if current:
                sections[current] = "\n".join(lines).strip()
            current = line[3:].strip()
            lines = []
        else:
            lines.append(line)
    if current:
        sections[current] = "\n".join(lines).strip()
    return sections

def load_faq():
    return _parse_md_sections(FAQ_PATH)

@st.cache_resource
def load_tooltips():
    tips = _parse_md_sections(TOOLTIPS_PATH)
    tips.update(_parse_faq_metric_definitions(FAQ_PATH))
    return tips


def _normalize_metric_tooltip_key(metric_name: str) -> str:
    mapping = {
        "Strategy Return (%)": "Strategy Return %",
        "Benchmark Return (%)": "Benchmark Return %",
        "CAGR (%)": "CAGR %",
        "Max Drawdown (%)": "Max Drawdown %",
        "Win Rate (%)": "Win %",
        "E[R] per Trade (%)": "E[R] per Trade %",
    }
    if metric_name in mapping:
        return mapping[metric_name]
    return metric_name.replace(" (%)", " %").strip()


def _parse_faq_metric_definitions(path: Path) -> dict[str, str]:
    """Extract Definition lines for performance metric tooltips from FAQ."""
    text = path.read_text(encoding="utf-8")
    section_patterns = [
        r"## What do the KPIs \(risk and performance metrics\) mean\?\n(.*)",
        r"## What do the performance metrics(?:/KPIs)? mean\?\n(.*)",
    ]
    section = None
    for pat in section_patterns:
        m = re.search(pat, text, flags=re.DOTALL)
        if m:
            section = m.group(1)
            break
    if section is None:
        return {}
    heading_re = re.compile(r"^\*\*(.+?)\*\*\s*$", flags=re.MULTILINE)
    matches = list(heading_re.finditer(section))
    out = {}
    for i, m in enumerate(matches):
        metric_name = m.group(1).strip()
        block_start = m.end()
        block_end = matches[i + 1].start() if i + 1 < len(matches) else len(section)
        block = section[block_start:block_end]
        definition_match = re.search(r"^Definition:\s*(.+)$", block, flags=re.MULTILINE)
        if definition_match:
            out[_normalize_metric_tooltip_key(metric_name)] = definition_match.group(1).strip()
    return out


# ═══════════════════════════════════════════════
# PAGE CONFIG
# ═══════════════════════════════════════════════

st.set_page_config(
    page_title="Bitcoin Breakout Strategy",
    page_icon="📊", layout="wide",
    initial_sidebar_state="collapsed",
)


# ═══════════════════════════════════════════════
# CSS — designed for 1920×1080
# ═══════════════════════════════════════════════

def inject_css():
    t = T()
    st.markdown(f"""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@600;700&family=Inter:wght@400;500;600;700&display=swap');
    #MainMenu {{visibility: hidden;}}
    header {{visibility: hidden;}}
    footer {{visibility: hidden;}}

    html, body, [class*="css"] {{
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
    }}
    .stApp, .main .block-container {{
        background-color: {t["bg"]}; color: {t["text"]};
    }}
    h1 {{
        font-family: 'Instrument Sans', 'Inter', sans-serif;
        color: {t["heading"]}; font-weight: 700; letter-spacing: -0.02em;
        border-bottom: 3px solid {t["gold"]}; padding-bottom: 4px;
        font-size: 1.4rem; margin-bottom: 0.2rem; margin-top: 0;
    }}
    h2 {{ color: {t["heading"]}; font-weight: 600; font-size: 1.0rem; margin-top: 0.3rem; margin-bottom: 0.2rem; }}
    h3 {{ color: {t["subheading"]}; font-weight: 600; font-size: 0.85rem; margin-top: 0.2rem; margin-bottom: 0.1rem; }}
    p, li, span {{ color: {t["text"]}; }}

    /* KPI cards */
    .kpi-container {{ display:flex; flex-wrap:wrap; gap:6px; margin:4px 0; overflow: visible; }}
    .kpi-card {{
        flex:1 1 80px; background:{t["surface"]}; border:1px solid {t["border"]};
        border-radius:6px; padding:6px 4px; text-align:center; min-width:70px;
        position: relative; cursor: help; overflow: visible;
    }}
    .kpi-label {{
        font-size:0.5rem; color:{t["text_muted"]}; text-transform:uppercase;
        letter-spacing:0.05em; margin-bottom:1px;
    }}
    .kpi-value {{ font-size:0.9rem; font-weight:700; color:{t["text"]}; }}
    .kpi-positive {{ color: {t["green"]}; }}
    .kpi-negative {{ color: {t["red"]}; }}
    .kpi-card .kpi-tip {{
        visibility: hidden; opacity: 0;
        background-color: {t["surface2"]}; color: {t["text"]};
        border: 1px solid {t["border"]}; border-radius: 6px;
        padding: 10px 14px; font-size: 0.75rem; line-height: 1.6;
        width: min(320px, calc(100vw - 32px)); max-width: calc(100vw - 32px);
        box-sizing: border-box; position: absolute; z-index: 1000;
        top: 100%; left: 50%; transform: translateX(-50%);
        margin-top: 6px;
        white-space: pre-line; transition: opacity 0.15s; pointer-events: none;
    }}
    /* First/last cards in the strip: anchor tooltip so wide tips stay on-screen */
    .kpi-container > .kpi-card:first-child .kpi-tip {{
        left: 0; transform: none;
    }}
    .kpi-container > .kpi-card:last-child .kpi-tip {{
        left: auto; right: 0; transform: none;
    }}
    .kpi-card:hover .kpi-tip {{ visibility: visible; opacity: 1; }}

    /* Expanders */
    div[data-testid="stExpander"] {{
        border: 1px solid {t["border"]}; border-radius: 8px;
        background-color: {t["surface"]};
    }}
    div[data-testid="stExpander"] summary span {{ color: {t["text"]}; }}

    /* Tabs */
    .stTabs {{ position: relative; }}
    .stTabs [data-baseweb="tab-list"] {{
        gap: 0; border-bottom: 2px solid {t["border"]};
    }}
    .stTabs [data-baseweb="tab"] {{
        color: {t["text_muted"]}; background-color: transparent;
        border: none; padding: 10px 24px; font-weight: 500;
    }}
    .stTabs [aria-selected="true"] {{
        color: {t["gold"]}; border-bottom: 2px solid {t["gold"]};
        background-color: transparent; font-weight: 600;
    }}

    /* Top panel */
    .top-header {{
        background: {t["surface2"]};
        border-top: 1px solid {t["border"]};
        border-bottom: 1px solid {t["border"]};
        margin: -0.5rem -1rem 0.5rem -1rem;
        padding: 10px 20px;
        display: grid;
        grid-template-columns: 1fr 2fr 1fr;
        align-items: center;
    }}
    .top-header-brand {{
        font-family: 'Instrument Sans', 'Inter', sans-serif;
        font-size: 1.6rem;
        font-weight: 700;
        color: #ffffff;
        letter-spacing: -0.02em;
        justify-self: start;
    }}
    .top-header-center {{
        justify-self: center;
        text-align: center;
    }}
    .top-dashboard-title {{
        font-family: 'Instrument Sans', 'Inter', sans-serif;
        color: {t["heading"]};
        font-size: 1.1rem;
        font-weight: 700;
        line-height: 1.2;
    }}
    .selected-strat-line {{
        margin-top: 0.2rem;
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
        color: {t["heading"]};
        font-size: 1rem;
        font-weight: 600;
        line-height: 1.25;
        display: inline-flex;
        align-items: center;
        gap: 6px;
        cursor: help;
    }}
    @media (max-width: 1200px) {{
        .top-header {{
            grid-template-columns: 1fr;
            row-gap: 0.3rem;
            text-align: center;
        }}
        .top-header-brand {{
            justify-self: center;
        }}
    }}

    /* Selectbox — compact inside heatmap column */
    div[data-baseweb="select"] > div {{
        background-color: {t["surface"]}; border-color: {t["border"]}; color: {t["text"]};
        min-height: 28px !important; padding: 2px 8px !important;
        font-size: 0.75rem !important;
    }}
    .stSelectbox label {{
        color: {t["text_muted"]}; font-size: 0.65rem !important;
        margin-bottom: 0px !important;
    }}
    .stSelectbox {{ margin-bottom: 0px !important; }}

    /* Dataframe */
    div[data-testid="stDataFrame"] {{
        border: 1px solid {t["border"]}; border-radius: 6px;
    }}

    /* Terminal single-screen fit (1920×1080 target) */
    .block-container, .main .block-container,
    div[data-testid="stAppViewBlockContainer"] > div.block-container {{
        padding-top: 0.5rem !important; padding-bottom: 0 !important;
        max-width: 1920px !important;
        padding-left: 0.8rem !important;
        padding-right: 0.8rem !important;
    }}
    .stApp {{ overflow: hidden; height: 100vh; }}
    .stMain, [data-testid="stMain"] {{ overflow-y: auto; height: 100vh; }}
    .stAppHeader, [data-testid="stHeader"] {{
        display: none !important; height: 0 !important;
        min-height: 0 !important; padding: 0 !important;
    }}
    .stTabs [data-baseweb="tab-panel"] {{ padding-top: 0.2rem; }}
    div[data-testid="stVerticalBlock"] > div {{ gap: 0.15rem; }}

    /* Tooltip containers */
    .tooltip-container {{
        position: relative; display: inline-block;
    }}
    .tooltip-container .tooltip-text {{
        visibility: hidden; opacity: 0;
        background-color: {t["surface2"]}; color: {t["text"]};
        border: 1px solid {t["border"]}; border-radius: 6px;
        padding: 10px 14px; font-size: 0.78rem; line-height: 1.7;
        width: min(440px, 78vw); position: absolute; z-index: 1000;
        top: 110%; left: 50%; transform: translateX(-50%);
        white-space: pre-line; transition: opacity 0.15s; pointer-events: none;
    }}
    .tooltip-container:hover .tooltip-text {{
        visibility: visible; opacity: 1;
    }}
    .section-tip-wrap {{
        position: relative; display: inline-block;
    }}
    .section-tip-wrap .section-tip {{
        visibility: hidden; opacity: 0;
        background-color: {t["surface2"]}; color: {t["text"]};
        border: 1px solid {t["border"]}; border-radius: 6px;
        padding: 8px 12px; font-size: 0.75rem; line-height: 1.5;
        width: 340px; position: absolute; z-index: 1000;
        top: 110%; left: 0;
        white-space: pre-line; transition: opacity 0.15s; pointer-events: none;
    }}
    .section-tip-wrap:hover .section-tip {{
        visibility: visible; opacity: 1;
    }}

    /* Gold highlight for selected (first) row in Strategy Table data_editor.
       Glide Data Grid doesn't expose per-row CSS, so we inject a subtle
       gold left-border on the table container when a row is selected. */
</style>
""", unsafe_allow_html=True)


# ═══════════════════════════════════════════════
# PLOTLY LAYOUT HELPERS
# ═══════════════════════════════════════════════

def _base_layout():
    t = T()
    return dict(
        font=dict(family="Inter, -apple-system, sans-serif", color=t["text"], size=11),
        paper_bgcolor=t["chart_paper"], plot_bgcolor=t["chart_bg"],
        margin=dict(l=50, r=10, t=25, b=25),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0,
                    font=dict(color=t["text"], size=10)),
        xaxis=dict(gridcolor=t["grid"], zeroline=False, color=t["text_muted"]),
        yaxis=dict(gridcolor=t["grid"], zeroline=False, color=t["text_muted"]),
    )

def _layout(**kw):
    d = _base_layout(); d.update(kw); return d


# ═══════════════════════════════════════════════
# SECTION TITLE WITH TOOLTIP
# ═══════════════════════════════════════════════

def _section_title(title, tips):
    """Render section title as h3 with tooltip icon in same row + same color."""
    t = T()
    tip = tips.get(title, "")
    if tip:
        st.markdown(
            f'<div class="section-tip-wrap" style="cursor:help;white-space:nowrap;">'
            f'<span style="color:{t["heading"]};font-weight:600;font-size:1rem;">{title}</span>'
            f'<span style="color:{t["heading"]};font-size:0.75rem;margin-left:5px;">ⓘ</span>'
            f'<div class="section-tip">{tip}</div></div>',
            unsafe_allow_html=True)
    else:
        st.markdown(
            f'<span style="color:{t["heading"]};font-weight:600;font-size:1rem;">{title}</span>',
            unsafe_allow_html=True)


# ═══════════════════════════════════════════════
# SELECTED STRATEGY LABEL (centered)
# ═══════════════════════════════════════════════

def _strategy_number_map(results_df):
    combos = results_df[["x", "y", "window"]].drop_duplicates()
    combos = combos.sort_values(["x", "y", "window"]).reset_index(drop=True)
    return {(int(r.x), int(r.y), int(r.window)): i + 1 for i, r in combos.iterrows()}


def render_selected_label(key, strat_num, tips):
    """Build selected strategy HTML line with tooltip for top panel."""
    tip = tips.get("Selected Strategy", "")
    return (
        f'<div class="tooltip-container">'
        f'<div class="selected-strat-line">'
        f'Selected: Strategy #{strat_num}'
        f'<span style="font-size:0.75rem;">ⓘ</span>'
        f'</div>'
        f'<div class="tooltip-text">{tip}</div>'
        f'</div>'
    )


# ═══════════════════════════════════════════════
# UNIFIED COLUMN/METRIC ORDER (Beta before Alpha)
# ═══════════════════════════════════════════════

_METRIC_ORDER = [
    ("Strategy Return %",   "strategy_return",  "%",  True),
    ("Benchmark Return %",  "benchmark_return",  "%",  True),
    ("Beta",                "beta",              "",   False),
    ("Alpha",               "alpha",             "",   False),
    ("CAGR %",              "cagr",              "%",  True),
    ("Max Drawdown %",      "max_dd",            "%",  True),
    ("Calmar Ratio",        "calmar",            "",   False),
    ("Trades",              "num_trades",        "",   False),
    ("Win %",               "win_rate",          "%",  True),
    ("Win/Loss Ratio",      "wl_ratio",          "",   False),
    ("Profit Factor",       "profit_factor",     "",   False),
    ("E[R] per Trade %",    "expected_return",   "%",  True),
]

_PCT_METRICS = {"strategy_return", "cagr", "max_dd", "win_rate", "expected_return", "benchmark_return"}


# ═══════════════════════════════════════════════
# CHART BUILDERS
# ═══════════════════════════════════════════════

def make_heatmap(results_df, metric, metric_label, window_slice, sel_x, sel_y, sel_win):
    t = T()
    filt = results_df[results_df["window"] == window_slice]
    pivot = filt.pivot_table(index="y", columns="x", values=metric, aggfunc="first")
    pivot = pivot.sort_index(ascending=True)

    xs = [str(c) for c in pivot.columns]
    ys = [str(i) for i in pivot.index]

    shapes = []
    if sel_x is not None and sel_y is not None and window_slice == sel_win:
        sx, sy = str(sel_x), str(sel_y)
        if sx in xs and sy in ys:
            xi = xs.index(sx)
            yi = ys.index(sy)
            shapes.append(dict(
                type="rect", x0=xi-0.5, x1=xi+0.5, y0=yi-0.5, y1=yi+0.5,
                line=dict(color=t["gold"], width=3)))

    fig = go.Figure()

    dp = 1 if metric in _PCT_METRICS else 2
    fig.add_trace(go.Heatmap(
        z=pivot.values, x=xs, y=ys,
        text=np.round(pivot.values, dp).astype(str),
        texttemplate="%{text}", textfont=dict(size=10),
        xgap=2, ygap=2,
        colorscale=[[0, t["red"]], [0.5, t["surface"]], [1, t["green"]]],
        colorbar=dict(title=dict(text=metric_label, font=dict(size=10, color=t["text_muted"])),
                      tickfont=dict(color=t["text_muted"]), thickness=12, len=0.8),
        hoverongaps=False,
    ))

    # Invisible scatter for click detection — one square marker per cell.
    # At 210px chart height (margins t=10,b=35 → ~165px plot), 5 rows →
    # ~33px/cell.  5 cols in ~370px → ~74px/cell.  Marker size = min
    # dimension so the click-target cannot bleed into a neighbouring cell.
    n_rows, n_cols = len(ys), len(xs)
    plot_h = 210 - 10 - 35          # ~165 px
    plot_w = 370                     # approximate (col width minus axes/colorbar)
    cell_h = plot_h / max(n_rows, 1)
    cell_w = plot_w / max(n_cols, 1)
    marker_sz = max(8, int(min(cell_h, cell_w) - 2))  # fill cell, 2px safety

    scatter_x, scatter_y, scatter_custom = [], [], []
    for yi_val in ys:
        for xi_val in xs:
            scatter_x.append(xi_val)
            scatter_y.append(yi_val)
            scatter_custom.append([int(xi_val), int(yi_val)])

    fig.add_trace(go.Scatter(
        x=scatter_x, y=scatter_y, mode="markers",
        marker=dict(size=marker_sz, color="rgba(0,0,0,0)", symbol="square",
                    line=dict(width=0)),
        customdata=scatter_custom,
        hovertemplate="Buy (x)=%{customdata[0]}, Sell (y)=%{customdata[1]}<extra></extra>",
        showlegend=False,
    ))

    # Heatmap height: compact so title + selectors + chart fit ~280px box.
    fig.update_layout(
        **_layout(
            height=210, shapes=shapes,
            clickmode="event+select",
            margin=dict(l=50, r=10, t=10, b=35),
            xaxis=dict(title=dict(text="Buy (x)", standoff=6),
                       type="category", gridcolor=t["grid"]),
            yaxis=dict(title="Sell (y)", type="category", gridcolor=t["grid"]),
        ))
    return fig


def make_equity(cd, compact=False):
    t = T()
    fig = go.Figure()
    strat_eq = np.array(cd["strat_equity"])
    bh_eq = np.array(cd["bh_equity"])
    s0 = strat_eq[0] if strat_eq[0] != 0 else 1
    b0 = bh_eq[0] if bh_eq[0] != 0 else 1
    fig.add_trace(go.Scatter(x=cd["dates"], y=strat_eq / s0,
                             name="Strategy", line=dict(color=t["gold"], width=2)))
    fig.add_trace(go.Scatter(x=cd["dates"], y=bh_eq / b0,
                             name="Buy & Hold", line=dict(color=t["text_muted"], width=1.5, dash="dot")))
    h = 280 if compact else 340
    fig.update_layout(**_layout(height=h,
                                yaxis=dict(title="Index (start = 1)", gridcolor=t["grid"])))
    return fig


def make_drawdown(cd, compact=False):
    t = T()
    r, g, b = _hex_to_rgb(t["red"])
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=cd["dates"], y=cd["strat_dd"], name="Strategy DD", fill="tozeroy",
        line=dict(color=t["red"], width=1.5), fillcolor=f"rgba({r},{g},{b},0.10)"))
    fig.add_trace(go.Scatter(x=cd["dates"], y=cd["bh_dd"],
                             name="Buy & Hold DD", line=dict(color=t["text_muted"], width=1, dash="dot")))
    h = 280 if compact else 340
    fig.update_layout(**_layout(height=h,
                                yaxis=dict(title="Drawdown (%)", gridcolor=t["grid"])))
    return fig


def _add_candlestick_volume(fig, cd, dates_range=None, row_price=1, row_vol=2,
                            show_legend_candle=False):
    t = T()
    if dates_range is not None:
        sl = dates_range
        d = [cd["dates"][i] for i in range(sl.start, sl.stop)]
        o, h, lo, c, v = (cd["open_price"][sl], cd["high"][sl],
                           cd["low"][sl], cd["close"][sl], cd["volume"][sl])
    else:
        d, o, h, lo, c, v = (cd["dates"], cd["open_price"], cd["high"],
                              cd["low"], cd["close"], cd["volume"])

    fig.add_trace(go.Candlestick(
        x=d, open=o, high=h, low=lo, close=c,
        increasing_line_color=t["green"], decreasing_line_color=t["red"],
        increasing_fillcolor=t["green"], decreasing_fillcolor=t["red"],
        name="OHLC", showlegend=show_legend_candle,
    ), row=row_price, col=1)

    vol_colors = [t["green"] if (c[i] is not None and o[i] is not None and c[i] >= o[i])
                  else t["red"] for i in range(len(c))]
    fig.add_trace(go.Bar(x=d, y=v, marker_color=vol_colors, opacity=0.4,
                         name="Volume", showlegend=False), row=row_vol, col=1)


def make_single_trade(trade, cd, sel_x=None, sel_y=None, height=270):
    """Trade Analysis chart — candlestick + volume with BB, bands, stop loss."""
    t = T()
    mr, mg, mb = _hex_to_rgb(t["text_muted"])
    dates = cd["dates"]
    entry_date, exit_date = trade["entry_date"], trade["exit_date"]
    si, ei = 0, len(dates) - 1
    for i, d in enumerate(dates):
        if d >= entry_date: si = i; break
    for i in range(len(dates)-1, -1, -1):
        if dates[i] <= exit_date: ei = i; break
    si, ei = max(0, si-10), min(len(dates)-1, ei+10)
    sl = slice(si, ei+1)
    x_eq_y = sel_x is not None and sel_y is not None and sel_x == sel_y

    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.02,
                        row_heights=[0.75, 0.25])

    # legendrank: lower = higher in legend. Desired order: Buy, Sell, Entry, Exit, Stop, BB.
    _LR_BUY, _LR_SELL, _LR_ENTRY, _LR_EXIT, _LR_STOP, _LR_BB = 1, 2, 3, 4, 5, 6

    bb_alpha = t["bb_fill_alpha"]
    if cd.get("bb_upper") and cd.get("bb_lower"):
        fig.add_trace(go.Scatter(x=dates[sl], y=cd["bb_upper"][sl], name="BB Upper",
                                 line=dict(color="rgba(0,0,0,0)", width=0), showlegend=False), row=1, col=1)
        fig.add_trace(go.Scatter(x=dates[sl], y=cd["bb_lower"][sl], name="Standard Bollinger Bands (±2σ)",
                                 legendrank=_LR_BB,
                                 fill="tonexty", fillcolor=f"rgba({mr},{mg},{mb},{bb_alpha})",
                                 line=dict(color="rgba(0,0,0,0)", width=0)), row=1, col=1)

    band_color = t["marker_buy_sell"]
    if x_eq_y:
        fig.add_trace(go.Scatter(x=dates[sl], y=cd["entry_band"][sl], name="Entry Band",
                                 legendrank=_LR_ENTRY,
                                 line=dict(color=band_color, width=1.2)), row=1, col=1)
        fig.add_trace(go.Scatter(x=dates[sl], y=cd["exit_band"][sl], name="Exit Band",
                                 legendrank=_LR_EXIT,
                                 line=dict(color=band_color, width=1.2, dash="dash")), row=1, col=1)
    else:
        fig.add_trace(go.Scatter(x=dates[sl], y=cd["exit_band"][sl], name="Exit Band",
                                 legendrank=_LR_EXIT,
                                 line=dict(color=band_color, width=1.2, dash="dash")), row=1, col=1)
        fig.add_trace(go.Scatter(x=dates[sl], y=cd["entry_band"][sl], name="Entry Band",
                                 legendrank=_LR_ENTRY,
                                 line=dict(color=band_color, width=1.2)), row=1, col=1)

    # Stop loss line — ONLY until exit day
    sll = cd.get("stop_loss_levels")
    if sll:
        sl_x_pts, sl_y_pts = [], []
        for j in range(sl.start, sl.stop):
            d_val = dates[j]
            v = sll[j]
            if v is not None and d_val <= exit_date:
                sl_x_pts.append(d_val)
                sl_y_pts.append(v)
        if sl_x_pts:
            fig.add_trace(go.Scatter(x=sl_x_pts, y=sl_y_pts, name="Stop Loss",
                                     legendrank=_LR_STOP,
                                     line=dict(color=t["red"], width=1.2, dash="dot"),
                                     mode="lines"), row=1, col=1)

    _add_candlestick_volume(fig, cd, dates_range=sl, row_price=1, row_vol=2)

    marker_color = t["marker_buy_sell"]
    fig.add_trace(go.Scatter(
        x=[exit_date], y=[trade["exit_price"]], mode="markers+text", name="Sell",
        legendrank=_LR_SELL,
        marker=dict(symbol="triangle-down", size=12, color=marker_color),
        text=[f"Sell ${trade['exit_price']:,.0f}"], textposition="bottom center",
        textfont=dict(size=10, color=marker_color)), row=1, col=1)
    fig.add_trace(go.Scatter(
        x=[entry_date], y=[trade["entry_price"]], mode="markers+text", name="Buy",
        legendrank=_LR_BUY,
        marker=dict(symbol="triangle-up", size=12, color=marker_color),
        text=[f"Buy ${trade['entry_price']:,.0f}"], textposition="top center",
        textfont=dict(size=10, color=marker_color)), row=1, col=1)

    sign = "+" if trade["return_pct"] >= 0 else ""
    clr = t["green"] if trade["return_pct"] >= 0 else t["red"]
    cr, cg, cb = _hex_to_rgb(clr)

    base = _base_layout()
    legend_cfg = {**base["legend"], "traceorder": "normal"}
    fig.update_layout(
        height=height,
        font=base["font"], paper_bgcolor=base["paper_bgcolor"],
        plot_bgcolor=base["plot_bgcolor"],
        margin=dict(l=50, r=10, t=76, b=25),
        legend={**legend_cfg, "y": 1.0, "yanchor": "bottom"},
        title=dict(
            text=f"Trade #{trade['trade']}: {sign}{trade['return_pct']}% ({sign}${trade['pnl']:,.0f})",
            font=dict(color=clr, size=13),
            x=0.5, xanchor="center", y=0.98, yanchor="top",
        ),
        xaxis_rangeslider_visible=False, xaxis2_rangeslider_visible=False,
        shapes=[
            dict(type="rect", x0=entry_date, x1=exit_date, y0=0, y1=1, yref="y domain",
                 fillcolor=f"rgba({cr},{cg},{cb},{t['trade_fill_alpha']})",
                 line=dict(width=0), layer="below"),
            dict(type="line", x0=entry_date, x1=entry_date, y0=0, y1=1, yref="y domain",
                 line=dict(color=t["marker_buy_sell"], width=1, dash="dot")),
            dict(type="line", x0=exit_date, x1=exit_date, y0=0, y1=1, yref="y domain",
                 line=dict(color=t["marker_buy_sell"], width=1, dash="dot")),
        ],
    )
    fig.update_yaxes(title_text="Price (USD)", gridcolor=t["grid"], zeroline=False,
                     color=t["text_muted"], row=1, col=1)
    fig.update_yaxes(title_text="", gridcolor=t["grid"], zeroline=False,
                     color=t["text_muted"], showticklabels=False, row=2, col=1)
    fig.update_xaxes(gridcolor=t["grid"], zeroline=False, color=t["text_muted"])
    return fig


# ═══════════════════════════════════════════════
# KPI CARDS (with tooltips from tooltips.md)
# ═══════════════════════════════════════════════

def render_trades_kpis(m, tips):
    t = T()
    alpha_dec = m["alpha"] / 100.0
    cards = [
        ("Strategy Return",   m["strategy_return"],  "%",  True,  "Strategy Return %"),
        ("Benchmark Return",  m["benchmark_return"],  "%",  True,  "Benchmark Return %"),
        ("Beta",              m["beta"],              "",   None,  "Beta"),
        ("Alpha",             alpha_dec,              "",   True,  "Alpha"),
        ("CAGR",              m["cagr"],              "%",  True,  "CAGR %"),
        ("Max Drawdown",      -abs(m["max_dd"]),      "%",  False, "Max Drawdown %"),
        ("Calmar Ratio",      m["calmar"],            "",   True,  "Calmar Ratio"),
        ("Trades",            m["num_trades"],        "",   None,  "Trades"),
        ("Win Rate",          m["win_rate"],          "%",  True,  "Win %"),
        ("Win/Loss Ratio",    m["wl_ratio"],          "",   True,  "Win/Loss Ratio"),
        ("Profit Factor",     m["profit_factor"],     "",   True,  "Profit Factor"),
        ("E[R] per Trade",    m["expected_return"],   "%",  True,  "E[R] per Trade %"),
    ]
    _PCT = {"Strategy Return", "Benchmark Return", "CAGR", "Max Drawdown", "Win Rate", "E[R] per Trade"}
    html = '<div class="kpi-container">'
    for label, val, sfx, pos_good, tip_key in cards:
        cls = ""
        if pos_good is True:
            cls = "kpi-positive" if val > 0 else ("kpi-negative" if val < 0 else "")
        elif pos_good is False:
            cls = "kpi-negative" if val < 0 else ""
        if isinstance(val, float):
            if label == "Trades":
                fmt = f"{val:.0f}"
            elif label in _PCT:
                fmt = f"{val:.1f}"
            else:
                fmt = f"{val:.2f}"
        else:
            fmt = str(val)
        tip = tips.get(tip_key, "")
        html += (f'<div class="kpi-card"><div class="kpi-tip">{tip}</div>'
                 f'<div class="kpi-label">{label}</div>'
                 f'<div class="kpi-value {cls}">{fmt}{sfx}</div></div>')
    html += '</div>'
    st.markdown(html, unsafe_allow_html=True)


# ═══════════════════════════════════════════════
# TAB: FAQ
# ═══════════════════════════════════════════════

def tab_faq(faq_content):
    for question, answer in faq_content.items():
        with st.expander(question):
            st.markdown(answer)


# ═══════════════════════════════════════════════
# TAB: STRATEGIES
# ═══════════════════════════════════════════════

def tab_strategies(results_df, all_strats, best_key, strat_num_map, tips):
    t = T()
    sel_x = st.session_state.sel_x
    sel_y = st.session_state.sel_y
    sel_win = st.session_state.sel_win
    key = (sel_x, sel_y, sel_win)
    strat = all_strats.get(key)
    if strat is None:
        strat = all_strats[best_key]; key = best_key

    chart_data = strat["chart_data"]
    strat_num = strat_num_map.get(key, 0)

    # Prepare metric/window options
    windows = sorted(results_df["window"].unique())
    metric_map = {}
    for dn, ik, sfx, _ in _METRIC_ORDER:
        lbl = dn.replace(" %", " (%)") if sfx == "%" else dn
        metric_map[lbl] = ik
    metric_keys = list(metric_map.keys())
    calmar_idx = next(i for i, k in enumerate(metric_keys) if "Calmar" in k)

    # ══ Row 1: Heatmap (with selectors) | Equity Curve | Drawdown ══
    col_hm, col_eq, col_dd = st.columns(3)

    with col_hm:
        _section_title("Strategy Heatmap", tips)
        # Side-by-side compact selectors inside the heatmap box
        dd_cols = st.columns([2, 1])
        with dd_cols[0]:
            sel_metric_label = st.selectbox(
                "Key Performance Indicator", metric_keys, index=calmar_idx,
                key="hm_metric")
            sel_metric = metric_map[sel_metric_label]
        with dd_cols[1]:
            hm_win = st.selectbox("Window (z)", windows,
                                   index=windows.index(sel_win) if sel_win in windows else 0,
                                   key="hm_window")

        fig_hm = make_heatmap(results_df, sel_metric, sel_metric_label, hm_win,
                              sel_x, sel_y, sel_win)
        hm_event = st.plotly_chart(fig_hm, on_select="rerun",
                                    key="heatmap_click", width="stretch",
                                    selection_mode=["points"],
                                    config={"displaylogo": False,
                                            "modeBarButtonsToRemove": ["lasso2d"]})

        if hm_event and hm_event.selection and hm_event.selection.points:
            pt = hm_event.selection.points[0]
            cd_pt = pt.get("customdata")
            if cd_pt and isinstance(cd_pt, (list, tuple)) and len(cd_pt) >= 2:
                new_x, new_y = int(cd_pt[0]), int(cd_pt[1])
            else:
                try:
                    new_x, new_y = int(pt["x"]), int(pt["y"])
                except (ValueError, KeyError, TypeError):
                    new_x, new_y = sel_x, sel_y
            if new_x != sel_x or new_y != sel_y or hm_win != sel_win:
                st.session_state.sel_x = new_x
                st.session_state.sel_y = new_y
                st.session_state.sel_win = hm_win
                st.session_state.sel_trade_idx = 0
                st.rerun()

    with col_eq:
        _section_title("Equity Curve", tips)
        st.plotly_chart(make_equity(chart_data, compact=True), width="stretch",
                        config={"displaylogo": False})

    with col_dd:
        _section_title("Drawdown", tips)
        st.plotly_chart(make_drawdown(chart_data, compact=True), width="stretch",
                        config={"displaylogo": False})

    # ══ Row 2: Strategy Table (full width) ══
    _section_title("Strategy Table", tips)

    internal_cols = [mk for _, mk, _, _ in _METRIC_ORDER]
    display_names = [dn for dn, _, _, _ in _METRIC_ORDER]

    display_df = results_df[["x", "y", "window"] + internal_cols].copy()
    display_df["alpha"] = display_df["alpha"] / 100.0
    display_df.columns = ["Buy (x)", "Sell (y)", "Window (z)"] + display_names
    display_df = display_df.sort_values("Calmar Ratio", ascending=False).reset_index(drop=True)

    display_df.insert(0, "Strategy", display_df.apply(
        lambda r: strat_num_map.get((int(r["Buy (x)"]), int(r["Sell (y)"]), int(r["Window (z)"])), 0),
        axis=1))

    for dn, _, sfx, _ in _METRIC_ORDER:
        if sfx == "%":
            display_df[dn] = display_df[dn].round(1)
        elif dn == "Trades":
            display_df[dn] = display_df[dn].astype(int)
        else:
            display_df[dn] = display_df[dn].round(2)
    display_df["Trades"] = display_df["Trades"].astype(int)

    # Pin selected strategy to top
    sel_strat_num = strat_num_map.get(key, 0)
    sel_mask = display_df["Strategy"] == sel_strat_num
    if sel_mask.any():
        sel_row = display_df[sel_mask]
        rest = display_df[~sel_mask]
        display_df = pd.concat([sel_row, rest], ignore_index=True)

    # Select checkbox — True for first row (selected via heatmap or table)
    display_df.insert(0, "Select", False)
    if len(display_df) > 0:
        display_df.at[0, "Select"] = True

    # Column config with tooltips and number formats
    col_config = {
        "Select": st.column_config.CheckboxColumn("Select", width="small"),
        "Strategy": st.column_config.NumberColumn("Strategy",
                     help=tips.get("Strategy", ""), width="small", format="%d"),
        "Buy (x)": st.column_config.NumberColumn("Buy (x)", help=tips.get("Buy (x)", ""), format="%d"),
        "Sell (y)": st.column_config.NumberColumn("Sell (y)", help=tips.get("Sell (y)", ""), format="%d"),
        "Window (z)": st.column_config.NumberColumn("Window (z)", help=tips.get("Window (z)", ""), format="%d"),
    }
    for dn, _, sfx, _ in _METRIC_ORDER:
        tip = tips.get(dn, "")
        if dn == "Trades":
            col_config[dn] = st.column_config.NumberColumn(dn, help=tip, format="%d")
        elif sfx == "%":
            col_config[dn] = st.column_config.NumberColumn(dn, help=tip, format="%.1f")
        else:
            col_config[dn] = st.column_config.NumberColumn(dn, help=tip, format="%.2f")

    edited_df = st.data_editor(
        display_df,
        hide_index=True, height=290, width="stretch",
        key="strat_tbl",
        column_config=col_config,
        disabled=[c for c in display_df.columns if c != "Select"],
    )

    # Detect checkbox change
    if edited_df is not None:
        checked = edited_df[edited_df["Select"] == True]
        if len(checked) > 0:
            pick = checked.iloc[-1]
            new_x, new_y, new_win = int(pick["Buy (x)"]), int(pick["Sell (y)"]), int(pick["Window (z)"])
            if new_x != sel_x or new_y != sel_y or new_win != sel_win:
                st.session_state.sel_x = new_x
                st.session_state.sel_y = new_y
                st.session_state.sel_win = new_win
                st.session_state.sel_trade_idx = 0
                st.rerun()


# ═══════════════════════════════════════════════
# TAB: TRADES
# ═══════════════════════════════════════════════

def tab_trades(all_strats, best_key, strat_num_map, tips):
    t = T()
    sel_x = st.session_state.sel_x
    sel_y = st.session_state.sel_y
    sel_win = st.session_state.sel_win
    key = (sel_x, sel_y, sel_win)
    strat = all_strats.get(key)
    if strat is None:
        strat = all_strats[best_key]; key = best_key

    trades = strat["trades"]
    metrics = strat["metrics"]
    chart_data = strat["chart_data"]
    strat_num = strat_num_map.get(key, 0)

    _section_title("KPIs", tips)
    render_trades_kpis(metrics, tips)

    LOG_H, CHART_H = 380, 380
    col_log, col_chart = st.columns(2)

    with col_log:
        _section_title("Trade Log", tips)
        if trades:
            trades_df = pd.DataFrame(trades)
            trades_df.columns = ["Trade", "Entry Date", "Entry Price", "Exit Date",
                                 "Exit Price", "PnL ($)", "Return (%)", "Status"]
            trades_df["Duration"] = (
                pd.to_datetime(trades_df["Exit Date"]) - pd.to_datetime(trades_df["Entry Date"])
            ).dt.days
            trades_df = trades_df.drop(columns=["Status"])

            def color_return(val):
                if isinstance(val, (int, float)):
                    if val > 0: return f"color: {t['green']}"
                    if val < 0: return f"color: {t['red']}"
                return ""

            log_event = st.dataframe(
                trades_df.style
                .map(color_return, subset=["PnL ($)", "Return (%)"])
                .format({"Entry Price": "${:,.2f}", "Exit Price": "${:,.2f}",
                         "PnL ($)": "${:,.2f}", "Return (%)": "{:.2f}%"}),
                width="stretch", height=LOG_H,
                on_select="rerun", selection_mode="single-row",
                key="trade_table",
            )

            trade_idx = st.session_state.sel_trade_idx
            if log_event and log_event.selection and log_event.selection.rows:
                trade_idx = log_event.selection.rows[0]
                st.session_state.sel_trade_idx = trade_idx
        else:
            st.info("No trades generated for this parameter combination.")
            trade_idx = -1

    with col_chart:
        _section_title("Trade Analysis", tips)
        if trades and 0 <= st.session_state.sel_trade_idx < len(trades):
            sel_trade = trades[st.session_state.sel_trade_idx]
            st.plotly_chart(make_single_trade(sel_trade, chart_data,
                                              sel_x=sel_x, sel_y=sel_y, height=CHART_H),
                            width="stretch", config={"displaylogo": False})
        else:
            st.info("Select a trade to zoom in.")


# ═══════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════

def main():
    data = load_precomputed()
    faq_content = load_faq()
    tips = load_tooltips()
    grid_results = data["grid_results"]
    all_strats = data["all_strategies"]
    best_key = data["best_key"]
    results_df = pd.DataFrame(grid_results)
    strat_num_map = _strategy_number_map(results_df)

    if "sel_x" not in st.session_state:
        st.session_state.sel_x = best_key[0]
    if "sel_y" not in st.session_state:
        st.session_state.sel_y = best_key[1]
    if "sel_win" not in st.session_state:
        st.session_state.sel_win = best_key[2]
    if "sel_trade_idx" not in st.session_state:
        st.session_state.sel_trade_idx = 0
    inject_css()

    selected_key = (st.session_state.sel_x, st.session_state.sel_y, st.session_state.sel_win)
    selected_strat_num = strat_num_map.get(selected_key, 0)
    selected_html = render_selected_label(selected_key, selected_strat_num, tips)
    st.markdown(
        f"""
<div class="top-header">
  <div class="top-header-brand">Kaila</div>
  <div class="top-header-center">
    <div class="top-dashboard-title">Bitcoin Breakout Strategy</div>
    {selected_html}
  </div>
  <div></div>
</div>
""",
        unsafe_allow_html=True,
    )

    tab1, tab2, tab3 = st.tabs(["Strategies", "Trades", "FAQ"])
    with tab1:
        tab_strategies(results_df, all_strats, best_key, strat_num_map, tips)
    with tab2:
        tab_trades(all_strats, best_key, strat_num_map, tips)
    with tab3:
        tab_faq(faq_content)

if __name__ == "__main__":
    main()
